// src/lib/pdf-generator.ts
import { jsPDF } from 'jspdf'

export interface ReportData {
  childName: string
  childAge: string
  primaryLearningStyle: string
  scores: any
  recommendations: string[]
  strategies: string[]
}

export function generatePDFReport(data: ReportData): Uint8Array {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  })

  // Page setup
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  const lineHeight = 7
  let yPos = margin

  // Helper functions
  const addText = (text: string, fontSize = 12, style: 'normal' | 'bold' = 'normal') => {
    doc.setFont('helvetica', style)
    doc.setFontSize(fontSize)
    const lines = doc.splitTextToSize(text, pageWidth - 2 * margin)
    doc.text(lines, margin, yPos)
    yPos += lines.length * lineHeight
    return lines.length * lineHeight
  }

  const addSection = (title: string, content: string) => {
    // Check if we need a new page
    if (yPos > pageHeight - 40) {
      doc.addPage()
      yPos = margin
    }
    
    addText(title, 16, 'bold')
    yPos += 5
    addText(content, 11)
    yPos += 10
  }

  const addHeader = () => {
    // Header background
    doc.setFillColor(79, 70, 229) // Blue
    doc.rect(0, 0, pageWidth, 40, 'F')
    
    // Title
    doc.setTextColor(255, 255, 255) // White
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(20)
    doc.text(`${data.childName}'s Learning Assessment`, pageWidth/2, 25, { align: 'center' })
    
    // Reset color
    doc.setTextColor(0, 0, 0)
    yPos = 50
  }

  // Generate PDF content
  addHeader()

  // Executive Summary
  addSection(
    'Executive Summary',
    `This comprehensive assessment reveals that ${data.childName} (age ${data.childAge}) demonstrates a primary ${data.primaryLearningStyle} learning preference. The following report provides evidence-based strategies to support their academic success.`
  )

  // Learning Style Analysis
  addSection(
    'Primary Learning Style: ' + data.primaryLearningStyle,
    `Based on the assessment responses, ${data.childName} shows strongest alignment with ${data.primaryLearningStyle.toLowerCase()} learning approaches. This means they process and retain information most effectively through this modality.`
  )

  // Key Recommendations
  let recText = data.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join('\n\n')
  addSection('Key Recommendations', recText)

  // Implementation Strategies
  let stratText = data.strategies.map((strat, i) => `${i + 1}. ${strat}`).join('\n\n')
  addSection('Implementation Strategies', stratText)

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(128, 128, 128)
  doc.text('Generated by Vedyx Learning Assessment Tool', pageWidth/2, pageHeight - 10, { align: 'center' })
  
  return doc.output('arraybuffer')
}

export function generateEmailBody(childName: string, reportData: ReportData): string {
  const { primaryLearningStyle } = reportData
  
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <style>
        body { 
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
          line-height: 1.6; 
          color: #333; 
          margin: 0; 
          padding: 0;
          background: #f5f5f5;
        }
        .container { 
          max-width: 600px; 
          margin: 0 auto; 
          background: white;
        }
        .header { 
          background: linear-gradient(135deg, #4F46E5, #7C3AED);
          color: white; 
          padding: 30px 20px; 
          text-align: center;
        }
        .header h1 { 
          margin: 0; 
          font-size: 24px; 
          font-weight: 600;
        }
        .content { 
          padding: 30px 20px;
        }
        .summary-box {
          background: #EBF8FF;
          border: 1px solid #3B82F6;
          border-radius: 8px;
          padding: 20px;
          margin: 20px 0;
        }
        .highlight {
          background: #FEF3C7;
          border-left: 4px solid #F59E0B;
          padding: 15px;
          margin: 20px 0;
        }
        .pdf-info {
          background: #F0FDF4;
          border: 1px solid #10B981;
          border-radius: 8px;
          padding: 20px;
          margin: 20px 0;
        }
        ul { 
          padding-left: 20px; 
          margin: 15px 0;
        }
        li { 
          margin-bottom: 8px;
        }
        .footer {
          background: #F9FAFB;
          padding: 20px;
          text-align: center;
          color: #6B7280;
          font-size: 14px;
        }
        
        /* Mobile responsive */
        @media only screen and (max-width: 480px) {
          .container { 
            margin: 0;
            border-radius: 0;
          }
          .header, .content, .footer { 
            padding: 20px 15px;
          }
          .header h1 { 
            font-size: 20px;
          }
          .summary-box, .highlight, .pdf-info {
            margin: 15px -5px;
            padding: 15px;
          }
        }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>🌟 ${childName}'s Learning Assessment Results</h1>
        </div>
        
        <div class="content">
          <p>Hi there!</p>
          
          <p>Great news! We've completed ${childName}'s comprehensive learning assessment, and the results show some fantastic insights about how they learn best.</p>
          
          <div class="summary-box">
            <h3 style="margin-top: 0; color: #1E40AF;">Quick Summary</h3>
            <p><strong>Primary Learning Style:</strong> ${primaryLearningStyle}</p>
            <p>This means ${childName} processes and retains information most effectively through ${primaryLearningStyle.toLowerCase()} approaches.</p>
          </div>
          
          <div class="highlight">
            <p><strong>📎 Your detailed PDF report is attached!</strong></p>
            <p>The attached PDF contains everything you need - it's formatted perfectly for reading on phones, tablets, and computers, plus it's print-ready for sharing with teachers.</p>
          </div>
          
          <h3>Your PDF Report includes:</h3>
          <ul>
            <li><strong>Detailed Learning Style Analysis</strong> - Understanding ${childName}'s processing preferences</li>
            <li><strong>Executive Function Assessment</strong> - How ${childName} organizes and manages tasks</li>
            <li><strong>Personalized Strategies</strong> - Specific techniques for home and school</li>
            <li><strong>Implementation Guide</strong> - Step-by-step approaches you can start using today</li>
            <li><strong>Teacher Sharing Tips</strong> - How to communicate these insights with educators</li>
          </ul>
          
          <div class="pdf-info">
            <h3 style="margin-top: 0; color: #059669;">Why PDF?</h3>
            <p>✓ Perfect formatting on all devices<br>
            ✓ Easy to print and share with teachers<br>
            ✓ Professional report you can reference anytime<br>
            ✓ No formatting issues on mobile devices</p>
          </div>
          
          <p>The strategies in this report are based on current research in neurodivergent-friendly education and have helped thousands of children improve their learning outcomes.</p>
          
          <p><strong>Next Steps:</strong></p>
          <ol>
            <li>Download and read the attached PDF</li>
            <li>Try 2-3 strategies that resonate most with you</li>
            <li>Share relevant sections with ${childName}'s teachers</li>
            <li>Give the strategies 2-3 weeks to show results</li>
          </ol>
          
          <p>Questions about the report? Simply reply to this email - we're here to help!</p>
          
          <p>Wishing ${childName} continued learning success,</p>
          <p><strong>The Vedyx Learning Assessment Team</strong></p>
        </div>
        
        <div class="footer">
          <p>📱 This email and PDF are optimized for mobile viewing</p>
          <p>Visit <a href="https://vedyx.ai" style="color: #4F46E5;">vedyx.ai</a> for more learning resources</p>
        </div>
      </div>
    </body>
    </html>
  `
}